export const UserActionTypes = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",
  GOOGLE_SIGN_IN_START: "user/GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START: "user/EMAIL_SIGN_IN_START",
  SIGN_SUCCESS: "user/SIGN_SUCCESS",
  SIGN_FAILED: "user/SIGN_FAILED",
  SIGN_UP_START: "user/SIGN_UP_START",
  SIGN_OUT_START: "user/SIGN_OUT_START",
};
